### ISSUE TITLE
Error in text rotation (OpenGL backend)

### ISSUE THREAD

**Issue by Frimkron** [Fiona/Myrmidon#51]
```
Traceback (most recent call last):
  File "feature_test.py", line 349, in <module>
    Application()
  File "/home/mark/venvs/myrmidon/local/lib/python2.7/site-packages/myrmidon/Entity.py", line 142, in __init__
    Game.run_game()
  File "/home/mark/venvs/myrmidon/local/lib/python2.7/site-packages/myrmidon/Game.py", line 221, in run_game
    cls.engine['window'].open_window()
  File "/home/mark/venvs/myrmidon/local/lib/python2.7/site-packages/myrmidon/engine/window/pygame/engine.py", line 81, in open_window
    self.callback(0.0)
  File "/home/mark/venvs/myrmidon/local/lib/python2.7/site-packages/myrmidon/Game.py", line 283, in app_loop_callback
    cls.engine['gfx'].draw_entities(cls.entity_draw_list)
  File "/home/mark/venvs/myrmidon/local/lib/python2.7/site-packages/myrmidon/engine/gfx/opengl/engine.py", line 102, in draw_entities
    list(map(self.draw_single_entity, self.entities_z_order_list))
  File "/home/mark/venvs/myrmidon/local/lib/python2.7/site-packages/myrmidon/engine/gfx/opengl/engine.py", line 177, in draw_single_entity
    entity.draw()
  File "/home/mark/venvs/myrmidon/local/lib/python2.7/site-packages/myrmidon/engine/gfx/opengl/engine.py", line 500, in draw
    y = draw_y + (entity.image.height/2) * self.scale
NameError: global name 'entity' is not defined
```

**Comment by Frimkron** [comment]
Fixed by d57d5b496d3588304928c3666bd6dd43d13d9c79
